### ISSUE TITLE
Clicking on "Edit" button causes an exception

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Content#12]
### Steps to reproduce

1. Start Content branch `compatibility-fix`
2. Start SignIn branch `Replace-ImageURL-with-Illustration-#58`
3. Go to `http://localhost:8080/signin/generateadminuser` to generate the admin user
4. Go to `http://localhost:8080/content/cms`
5. Sign in as admin user
6. Press the first "Edit" button

### Expected result

The content edit page should open without an error.

### Actual result

The content edit page opens with an error. More information is in Starcounter Administrator log:

```txt
Starcounter.XSON.JsonPatchException: Unknown property in path. Patch: '{""op"":""replace"",""path"":""/CurrentPage/Content/RedirectUrl$"",""value"":""/content/cms/item/C2""}'. Property: 'RedirectUrl$'. Viewmodel versions: {client (_ver#c$): 1, clients serverversion: 1, server (_ver#s): 2}.
   at Starcounter.XSON.JsonProperty.EvalutateCurrent(ViewModelVersion version) in C:\TeamCity\BuildAgent\work\sc-1355\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 177
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\BuildAgent\work\sc-1355\Level1\src\Starcounter\TransactionManager.cs:line 471
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-1355\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 68
   at Starcounter.XSON.JsonProperty.DoEvaluate(Json root) in C:\TeamCity\BuildAgent\work\sc-1355\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 88
   at Starcounter.XSON.JsonProperty.Evaluate(JsonPointer pointer, Json root) in C:\TeamCity\BuildAgent\work\sc-1355\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 62
   at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, String value) in C:\TeamCity\BuildAgent\work\sc-1355\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 19
   at Starcounter.XSON.JsonPatch.HandleOnePatch(Json root, JsonPatchOperation op, JsonPointer ptr, String value, Int32 patchCount, ChangeLog changeLog, Object sourceJson, Boolean strictRejection) in C:\TeamCity\BuildAgent\work\sc-1355\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 540
   at Starcounter.XSON.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount) in C:\TeamCity\BuildAgent\work\sc-1355\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 469
   at Starcounter.XSON.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount) in C:\TeamCity\BuildAgent\work\sc-1355\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 367
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(String bs, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-1355\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 59
Patch={""op"":""replace"",""path"":""/CurrentPage/Content/RedirectUrl$"",""value"":""/content/cms/item/C2""}
CurrentProperty=RedirectUrl$
Severity=1
HResult=-2146233088
```

##### Browsers affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Screenshot

![2017-01-20 23_16_43-content](https://cloud.githubusercontent.com/assets/566463/22167430/89e6bb14-df66-11e6-9c30-aa8311d4f59f.png)

**Comment by diliger** [comment]
first test:
error doesn't appear if Website application started
but appears if Website app is not started.

**Comment by diliger** [comment]
well, now i see the problem better.

it is inside `puppet-redirect` or patches engine.
here is what happens:
1) User clicks on the Edit button
2) script invokes and calls `template.set("model.RedirectUrl$", item.Href);`
3) redirect happens because of `<link is="puppet-redirect" history url$="{{model.RedirectUrl$}}" />` on the page
4) and now, **after redirect** patch with changes for the property `RedirectUrl` got sent to the server

but another page is loaded now, and it doesn't have `RedirectUrl` property, so we get an error in response.
that clearly says:
```
Unknown property in path.
CurrentProperty=RedirectUrl$
```

I can easily do a workaround but any ideas about the problem?

**Comment by warpech** [comment]
This turns out to be a very interesting client-side problem:

RedirectURL is changed by the event handler in the Polymer template like this:

```
template.set("model.RedirectUrl$", item.Href);
```

Because of that, a Polymer element (`puppet-redirect`) gets informed directly by Polymer about the redirection, even before PuppetJs dirty checking is informed about it.

The solution is to change the above line to:

```
template.model.RedirectUrl$ = item.Href;
```

This makes the change directly on the JS object. Polymer will be notified about it AFTER PuppetJs discovers it.

This should fix the problem. @diliger, is this the workaround you had in mind? Can you pls check the solution and make a PR?

**Comment by diliger** [comment]
yep, it is fixed now.
actually i had another workaround in my mind, but it is good now.

PR #13

**Comment by warpech** [comment]
Closing as done
